/* tslint:disable */
/* eslint-disable */
/**
 * Kafka Window API
 * This is a monitoring and analytics tool for Kafka.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlerErrorMessage,
} from '../models/index';
import {
    HandlerErrorMessageFromJSON,
    HandlerErrorMessageToJSON,
} from '../models/index';

export interface TopicsGetRequest {
    u?: string;
}

/**
 * 
 */
export class TopicsApi extends runtime.BaseAPI {

    /**
     * Get a list of all topics.
     */
    async topicsGetRaw(requestParameters: TopicsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/topics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['u'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get a list of all topics.
     */
    async topicsGet(requestParameters: TopicsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.topicsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
