/* tslint:disable */
/* eslint-disable */
/**
 * Kafka Window API
 * This is a monitoring and analytics tool for Kafka.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlerErrorMessage
 */
export interface HandlerErrorMessage {
    /**
     * 
     * @type {string}
     * @memberof HandlerErrorMessage
     */
    message?: string;
}

/**
 * Check if a given object implements the HandlerErrorMessage interface.
 */
export function instanceOfHandlerErrorMessage(value: object): value is HandlerErrorMessage {
    return true;
}

export function HandlerErrorMessageFromJSON(json: any): HandlerErrorMessage {
    return HandlerErrorMessageFromJSONTyped(json, false);
}

export function HandlerErrorMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlerErrorMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function HandlerErrorMessageToJSON(json: any): HandlerErrorMessage {
    return HandlerErrorMessageToJSONTyped(json, false);
}

export function HandlerErrorMessageToJSONTyped(value?: HandlerErrorMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

