definitions:
  handler.ErrorMessage:
    properties:
      message:
        type: string
    type: object
  model.CleanupPolicy:
    enum:
    - delete
    - compact
    - both
    - unknown
    type: string
    x-enum-varnames:
    - CleanupPolicyDelete
    - CleanupPolicyCompact
    - CleanupPolicyBoth
    - CleanupPolicyUnknown
  model.RetentionMs:
    properties:
      indefinite:
        type: boolean
      value:
        type: integer
    required:
    - indefinite
    - value
    type: object
  model.TopicDetails:
    properties:
      additionalConfigs:
        additionalProperties:
          type: string
        type: object
      cleanupPolicy:
        $ref: '#/definitions/model.CleanupPolicy'
      isInternal:
        type: boolean
      name:
        type: string
      numPartitions:
        type: integer
      replicationFactor:
        type: integer
      retentionBytes:
        type: integer
      retentionMs:
        $ref: '#/definitions/model.RetentionMs'
    required:
    - additionalConfigs
    - cleanupPolicy
    - isInternal
    - name
    - numPartitions
    - replicationFactor
    - retentionBytes
    - retentionMs
    type: object
info:
  contact: {}
  description: This is a monitoring and analytics tool for Kafka.
  title: Kafka Window API
  version: "1.0"
paths:
  /topics:
    get:
      consumes:
      - application/json
      parameters:
      - description: No parameters required
        in: body
        name: '-'
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of topic names
          schema:
            items:
              $ref: '#/definitions/model.TopicDetails'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorMessage'
      summary: Get a list of all topics.
      tags:
      - topics
swagger: "2.0"
